kliq_world/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from journey import views as journey_views
from journey import auth_views
from journey.forms import MyPasswordResetForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', journey_views.index, name='home'),
    url(r'^(?P<lang>[a-zA-Z]{2})/$', journey_views.index, name='home'),
    #url(r'^signinup/$', journey_views.signinup, name='signinup'),
    url(r'^(?P<lang>[a-zA-Z]{2})/signup/$', journey_views.signup, name='signup'),
    url(r'^(?P<lang>[a-zA-Z]{2})/signin/$', journey_views.signin, name='signin'),
    url(r'^(?P<lang>[a-zA-Z]{2})/signinup/$', journey_views.signup, name='signinup'),
    url(r'^activate/(?P<lang>[a-zA-Z]{2})/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', journey_views.activate, name='activate'),
    url(r'^logout/$', journey_views.logout, name='logout'),
    url(r'^profile/$', journey_views.profile, name='profile'),
    url(r'^change-lang/(?P<lang>[a-zA-Z]{2})$', journey_views.change_user_lang, name='change_lang'),
    url(r'^change-lang/(?P<lang>[a-zA-Z]{2})$', journey_views.change_user_lang, name='change_lang'),
    url(r'^delete-user-data/$', journey_views.delete_user_data, name='delete_user_data'),
    
    # Password reset links
    url(r'^user/password-reset/$', auth_views.password_reset, {'post_reset_redirect' : '/user/password-reset-done/', 'template_name' : 'registration/password_reset.html', 'password_reset_form' : MyPasswordResetForm, 'from_email': "info@kliq.ca", 'language':'en' }, name="password_reset_en"),
    url(r'^fr/user/password-reset/$', auth_views.password_reset, {'post_reset_redirect' : '/user/password-reset-done/', 'template_name' : 'registration/password_reset.html', 'password_reset_form' : MyPasswordResetForm, 'from_email': "info@kliq.ca", 'language':'fr' }, name="password_reset_fr"),
    url(r'^(?P<language>[a-zA-Z]{2})/user/password-reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, {'post_reset_redirect' : '/user/password-done/', 'template_name' : 'registration/password_reset_confirm.html' }, name='password_reset_confirm'),
    url(r'^user/password-reset-done/$', auth_views.password_reset_done, {'template_name': 'registration/password_reset_done.html'},),
    url(r'^user/password-done/$', auth_views.password_reset_complete, {'template_name': 'registration/password_reset_complete.html'}, name='password_done'),
    
    url(r'^process/$', journey_views.payment_process, name='payment_process'),
    url(r'^done/$', journey_views.payment_done, name='payment_done'),
    url(r'^cancelled/$', journey_views.payment_cancelled, name='payment_cancelled'),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^api/', include(('journey.api_urls', 'journey'), namespace='api')),

    # for testing
    # url(r'^gettoken/', journey_views.get_access_token),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

journey/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordResetForm
from journey.models import Profile, Country_Diploma
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from nocaptcha_recaptcha.fields import NoReCaptchaField

USER_TYPE = (
    ('', '---'),
    ("hs student", _("High school student")),
    ("uni student", _("University student")),
    ("parent", _("Parent")),
    ("counselor", _("Counselor")),
    ("other", _("Other")),
)

GENDER = (
    ('', '---'),
    ('female', _('Female')), 
    ('male', _('Male')), 
    ('nosay', _('Prefer not to say'))
)

SCHOOL_LANGUAGE = (
    ('english', _('Yes, English')), 
    ('french', _('Yes, French')), 
    ('no', _("No, I haven't"))
)

GRADES = (
    ('', '---'),
    (9, 9),
    (10, 10),
    (11, 11),
    (12, 12),
    (1, _('1st year')),
    (2, _('2nd year')),
    (3, _('3rd year')),
    (4, _('4th year')),
)

class RegistrationForm(UserCreationForm):
    
    name = forms.CharField(widget=forms.TextInput(attrs={'autocomplete': 'off', 'name':'name','spellcheck':'false'}))
    # email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'data-gtmtag': 'Email'}))
    email2 = forms.EmailField(required=True, widget=forms.EmailInput())
    password1 = forms.CharField(required=True, widget=forms.TextInput(attrs={'type':'password', 'autocomplete': 'off','spellcheck':'false'}))
    password2 = forms.CharField(required=True, widget=forms.TextInput(attrs={'type':'password', 'autocomplete': 'off','spellcheck':'false'}))
    school_language = forms.ChoiceField(widget=forms.RadioSelect, choices=SCHOOL_LANGUAGE)
    user_type = forms.ChoiceField(required=True, choices=USER_TYPE, widget=forms.Select(attrs={'data-gtmtag':'Are you a?'}))
    gender = forms.ChoiceField(required=True, choices=GENDER, widget=forms.Select(attrs={'data-gtmtag':'Gender'}))
    date_birth = forms.DateField(required=False, input_formats=['%m/%Y'], widget=forms.DateInput(attrs={'data-gtmtag':'Birth Month & Year'}))
    promo_code = forms.CharField(required=False, widget=forms.TextInput(attrs={'autocomplete': 'off', 'name':'promo_code','spellcheck':'false',}))
    # grade = forms.ChoiceField(required=False, choices=GRADES, widget=forms.Select(attrs={'data-gtmtag':'Grade'}))
    captcha = NoReCaptchaField()
    
    class Meta:
        model = Profile
        fields = ("name", "email", "email2", "password1", "password2", "user_type", "gender", "mother_tongue", "date_birth", "school_language", "grade", "city", "captcha", "promo_code")
    
    
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email2'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['grade'].widget.attrs['class'] = 'form-control'
        self.fields['user_type'].widget.attrs['class'] = 'form-control'
        self.fields['mother_tongue'].widget.attrs['class'] = 'form-control'
        self.fields['gender'].widget.attrs['class'] = 'form-control'
        self.fields['date_birth'].widget.attrs['class'] = 'form-control'
        self.fields['city'].widget.attrs['class'] = 'form-control'
        self.fields['promo_code'].widget.attrs['class'] = 'form-control'
        
        if self.instance.pk:
            self.fields['firstname'].required = True
            self.fields['lastname'].required = True
            self.fields['password1'].required = True
            self.fields['password2'].required = True 
    
    def clean_email(self):
        email = self.cleaned_data['email']
        if Profile.objects.filter(email__iexact=email).exists():
            raise ValidationError("This email has already been used!")
        return email

    
class CountryForm(forms.ModelForm):
    class Meta:
        model = Country_Diploma
        fields = ("country_name", "school_diploma")
        
        labels = {
            'name': 'Country'
        }      
 
class LoginForm(AuthenticationForm):
    
    username = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder':_('Email address'),}), error_messages= {"required": "Give yourself a username"})
    password = forms.CharField(required=True, widget=forms.TextInput(attrs={'type':'password', 'placeholder':_('Password'), }))
    
    
    class Meta:
        model = Profile
        fields = ("username", "password")
        error_messages= {
            "username" : {
        "required": "Give yourself a username"
        }
            
        }
        
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'
        
        self.fields['username'].widget.attrs['error_messages'] = {'required': 'Please enter your name'}
        self.fields['password'].widget.attrs['error_messages'] = {'required': 'Please enter your password'}        
     
        
        
class MyPasswordResetForm(PasswordResetForm):
    
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder':_('Email address'), 'type':'email'}))
    
    def __init__(self, *args, **kwargs):
        super(MyPasswordResetForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['class'] = 'form-control'
        
    def clean_email(self):
        email = self.cleaned_data['email']
        if not Profile.objects.filter(email__iexact=email).exists():
            raise ValidationError(_("There is no user registered with the specified email address!"))
        
        return email

templates/base.html
{% load staticfiles %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html>
    <head>

        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta property="og:title" content="KLIQ.CA" />
        <meta property="og:description" content="KLIQ is The cognitive modeling tool integrating grades, personality, probability, and decision trees, for the educational and career journey." /> 
        
        <title>{% block title %}  {% endblock %}</title>
        
        <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
        <link href="{% static 'vendors/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/angular-ui-bootstrap/dist/ui-bootstrap-csp.css' %}" rel="stylesheet" type="text/css">
        
        {% block topcss %}  {% endblock topcss %}
        
        <script>
            (function(i,s,o,g,r,a,m){
            i['GoogleAnalyticsObject']=r;
            i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},
            i[r].l=1*new Date();
            a=s.createElement(o),m=s.getElementsByTagName(o)[0];
            a.async=1;
            a.src=g;
            m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
            
            ga('create', 'UA-132112457-1', 'auto');
            ga('send', 'pageview');
        </script>

         <!-- Google Tag Manager -->
          <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-57XT3ZL');</script>
         <!-- End Google Tag Manager -->
    
        {% block topjs %} {% endblock topjs %}
        
    </head>
    
    <body>
             
        <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-57XT3ZL"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->
        
        {% block gtmpush %} {% endblock gtmpush %}
        


<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
    {% if user.is_authenticated %}
      <a class="lineborder" >{% trans "Close" %}</a>
    <a class="lineborder" href="{% url 'profile' %}">Profile</a>
    {% if LANGUAGE_CODE == 'fr' %}
    <a class="lineborder" href="{% url 'home' 'fr' %}">MYKLIQ</a>
    <a class="lineborder" href="https://kliq.ca/conditions-dutilisation/">{% trans "Terms Of Use" %}</a>
    <a class="lineborder"  href="https://kliq.ca/fr-team/">{% trans "About Us" %}</a>
    {% else %}
    <a class="lineborder" href="{% url 'home'%}">MYKLIQ</a>
    <a class="lineborder" href="https://kliq.ca/terms/">{% trans "Terms Of Use" %}</a>
    <a class="lineborder" href="https://kliq.ca/team/">{% trans "About Us" %}</a>
    {% endif %}
    <a class="lineborder" href="https://kliq.ca/blog/">Blog</a>
    <a class="lineborder" href="{% url 'logout' %}">{% trans "Logout" %}</a>
    {% else %}
    <a class="lineborder" >{% trans "Close" %}</a>
    <a class="lineborder" href="{% url 'signin' LANGUAGE_CODE %}">{% trans "Log in" %}</a>
    {% if LANGUAGE_CODE == 'fr' %}
    <a class="lineborder" href="{% url 'home' 'fr' %}">MYKLIQ</a>
    <a class="lineborder" href="https://kliq.ca/conditions-dutilisation/">{% trans "Terms Of Use" %}</a>
    <a class="lineborder"  href="https://kliq.ca/fr-team/">{% trans "About Us" %}</a>
    {% else %}
    <a class="lineborder" href="{% url 'home'%}">MYKLIQ</a>
    <a class="lineborder" href="https://kliq.ca/terms/">{% trans "Terms Of Use" %}</a>
    <a class="lineborder" href="https://kliq.ca/team/">{% trans "About Us" %}</a>
    {% endif %}
    <a class="lineborder" href="{% url 'signup' LANGUAGE_CODE %}">{% trans "Register" %}</a>
    <a class="lineborder" href="https://kliq.ca/blog/">Blog</a>
    {% endif %}
</div>
<div class="container-fluid">
    <div class="row" style="background-color:#f4f7f6;">
        <div class="col-md-12 text-center" id="menuNav">
            <div class="row" style="height:36px;">
                <div class="col-xs-4 col-md-5 col-lg-6" style="text-align: left;">
                                   
                    <div class="menubutton" onclick="openNav()">☰ MENU</div>
                     <!--<div style="margin-top:-40px;border-right: 1px solid grey; height: 55px;"></div>-->
                  </div> 
                <div class="col-xs-4 col-md-2 col-lg-1" id="brand" style="text-align: left; margin-top:5px;">
                 <a class="navbar-brand" href="/">KLIQWorld</a>
                </div>  
                {% if user.is_authenticated %}
               <div class="col-xs-2 col-md-2 col-lg-1" style=" left:15px; text-align: right;  height:60px;" id="log">
               
                 <div class="menubutton" onclick="window.location.href='{% url 'logout' %}'">LOGOUT<img src="/static/img/Logout-icon.png" style="margin-left:5px;" width="15px";> </div>
                </div>
            <div class="col-xs-1 col-md-2 col-lg-1 green" style="left:0px; text-align: right; height:60px;" id="reg">
                  <div class="menubutton" onclick="window.location.href='{% url 'profile' %}'" >{% trans "PROFILE" %}</div>
                  </div> 
                
                <div class="col-xs-4 col-md-2 col-lg-1" style="text-align: center;">
                    {% if LANGUAGE_CODE == 'fr' %}
                        <div class="menubutton"onclick="window.location.href='{% url 'home' 'en' %}'">ENGLISH</div> 
                   {% else %}
                        <div class="menubutton" onclick="window.location.href='{% url 'home' 'fr' %}'">{% trans "FRANÇAIS" %}</div> 
                    {% endif %}
                </div>
               {% else %}
                <div class="col-xs-2 col-md-2 col-lg-1" {% if LANGUAGE_CODE == 'fr' %} style="left:15px; text-align: right;height:60px;" {% else %} style="left:15px; text-align: right;height:60px;" {% endif %} id="log">
                  <div class="menubutton" onclick="window.location.href='{% url 'signin' LANGUAGE_CODE %}'">{% trans 'LOG IN' %}</div>
                </div>
                <div class="col-xs-1 col-md-2 col-lg-2" {% if LANGUAGE_CODE == 'fr' %}style="left:10px; text-align: center; height:60px;" {% else %} style="left:8px; text-align: center; height:55px;"{% endif %} id="reg">
                  <div class="menubutton" onclick="window.location.href='{% url 'signup' LANGUAGE_CODE %}'">{% trans "REGISTER" %}</div>
                </div>   
                
                <div class="col-xs-4 col-md-2 col-lg-1" style="text-align: left;">
                  {% if LANGUAGE_CODE == 'fr' %}
                      {% if request.path == '/fr/signup/' %}
                        <div class="menubutton" onclick="window.location.href='{% url 'signup' 'en' %}'">{% trans "ENGLISH" %}</div> 
                      {% endif %}
                      {% if request.path == '/fr/signin/' %}
                        <div class="menubutton" onclick="window.location.href='{% url 'signin' 'en' %}'">{% trans "ENGLISH" %}</div> 
                      {% endif %}
                  {% else %}
                      {% if request.path == '/en/signup/' %}
                        <div class="menubutton" onclick="window.location.href='{% url 'signup' 'fr' %}'">{% trans "FRANÇAIS" %}</div> 
                      {% endif %}
                      {% if request.path == '/en/signin/' %}
                        <div class="menubutton" onclick="window.location.href='{% url 'signin' 'fr' %}'">{% trans "FRANÇAIS" %}</div> 
                      {% endif %}
                  {% endif %}
                </div>
               {% endif %}
            </div>
        </div>
    </div>
</div>


    <script>       
    function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
    }

    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }

    function openNavR() {
        document.getElementById("mySidenavR").style.width = "250px";
    }

    function closeNavR() {
        document.getElementById("mySidenavR").style.width = "0";
    }
   </script>
        
        <div class='container'> 
                              
        {% block content %}
        {% endblock content %}
        
        </div> <!-- end of container -->
        
        <div id="footer">
            <span>{% trans "Made with ❤︎ and lots of" %}
              <img draggable="false" class="emoji" alt="☕" src="https://s.w.org/images/core/emoji/2.3/svg/2615.svg" style="width: 15px; text-align: inherit; margin: 0px 1px; font-size: 16px;">
              {% trans "in Ottawa/Toronto-" %} &copy; {% trans "2019 Kliq.ca Inc | All rights reserved" %}
              </span>
        </div>
        
        {% block bottomjs %}
        {% endblock bottomjs %}
        
    </body>
        
</html>
        
        
    
    
    

templates/signin.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}


    {% block title %} KLIQWorld Sign in {% endblock title %}
        
    {% block topcss %}
        <link href="https://fonts.googleapis.com/css?family=Muli:200,300,400,700" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Poppins:400,700" rel="stylesheet">
        <link href="{% static 'css/signin.css' %}" rel="stylesheet">
    {% endblock topcss %}
        
    
    {% block question %} {% trans "Don't have an account yet?" %} {% endblock question %}
    
    {% block buttonURL %}
        <a href="{% url 'signup' 'en' %}" class="signinbutton" name="signin">{% trans 'REGISTER FREE' %}</a>
    {% endblock buttonURL %}
    

    {% block content %}
        
        {% get_current_language as LANGUAGE_CODE %}
        
         <h1 class="welcome">{% trans "It's good to see you again" %}</h1>
         <br>
         <p id="welcomeMessage">{% trans "We are currently adding hundreds of careers and programs.<br>More options to find your perfect path. <br>Stay tuned for more updates.</p>" %}
          
            <div class="row" style="text-align:center">
                <div class='col-md-6 col-sm-4 col-md-offset-3 col-sm-offset-4'>
                        {% if form.non_field_errors %}
                        <div class="alert alert-danger">
                            {% for error in form.non_field_errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
                        {% endif %}
                        
                        <form action="" method="post"  >
                            {% csrf_token %}
                    		<label for="id_email">{% trans "Email" %}</label>
                              <!-- <input name="username" type="email" class="form-control" id="email" required> -->
                              {{ form.username }}
                    	     {% for error in form.username.errors %}
                                <div class="alert alert-danger"><p>{{ form.username.errors }}</p></div>
                              {% endfor %}
                    		<br>
                    	   
                    	    <label for="id_password">{% trans "Password" %}</label>
                             <!-- <input name="password" type="password" class="form-control" id="password" required> -->
                             {{ form.password }}
                             {% for error in form.password.errors %}
                                <div class="alert alert-danger" ><p>{{ form.password.errors }}</p></div>
                              {% endfor %}
                    		
                    		<input type="submit" value="{% trans 'Sign in' %}"   class="btn-primary"/>
                    		{% if LANGUAGE_CODE == 'fr' %}
                    		<a href="{% url 'password_reset_fr' %}">
							{% else %}
							<a href="{% url 'password_reset_en' %}">
							{% endif %}
                    		    <p style="text-align:center">{% trans "Forgot your password?" %}</p>
                    		</a>
                    		<a href="{% url 'signup' LANGUAGE_CODE %}">
                    		    <p style="text-align:center">{% trans "Create an account" %}</p>
                    		</a>
                    		
                        </form> <!-- end of sign in form -->
                        
                        

        
        
              </div> 
        </div>   
{% endblock content %}
{% block bottomjs %}

     <script src="{% static 'vendors/jquery/jquery.min.js' %}"></script> 
        <script>
                 $(document).ready(function() {
                     var url = window.location.href
                   var elements = document.getElementsByTagName("INPUT");
                    for (var i = 0; i < elements.length; i++) {
                        
                        elements[i].oninvalid = function(e) {
                            e.target.setCustomValidity("");
                            if (!e.target.validity.valid  && url.indexOf("/en/") >= 0) {
                                e.target.setCustomValidity("This field is required!");
                            } else if (!e.target.validity.valid   && url.indexOf("/fr/") >= 0){
                                e.target.setCustomValidity("Ce champ est obligatoire!");
                            }
                        };
                        elements[i].oninput = function(e) {
                            e.target.setCustomValidity("");
                        };
                        
                    }
                    
                })
        </script>
                        
{% endblock bottomjs %}